services:
  frontend:
    image: nginx:1.27.0
    volumes:
      - ./conf/nginx/templates:/etc/nginx/templates/
      - ./conf/nginx/includes/ssl.conf:/etc/nginx/includes/ssl.conf:ro
      - ./conf/nginx/ssl/opencart.crt:/etc/pki/tls/certs/opencart.crt:ro
      - ./conf/nginx/ssl/opencart.key:/etc/pki/tls/private/opencart.key:ro
      - ./www/html:/var/www/html:rw
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cms-network
    environment:
      - FASTCGI_PASS_HOST=php-fpm
      - NGINX_HOST=opencart-my-store
      - NGINX_HOST1=frontend
      - NGINX_PORT=80
      - NGINX_PORT_SSL=443
      - STUB_STATUS_PORT=8008
      - STUB_STATUS_HOST=frontend
    depends_on:
      - database
    command: [nginx, '-g', 'daemon off;']
    restart: always

  php-fpm:
    build: ./build/php/
    volumes:
       - ./www/html:/var/www/html:rw
       - ./conf/php-fpm/status.conf:/usr/local/etc/php-fpm.d/status.conf:ro
    ports:
      - "9000:9000"
    networks:
      - cms-network
    depends_on:
      - database
    command: >
      sh -c "if [ ! -f /var/www/html/www/install.lock ]; then
               wait-for-it database:3306 -t 60 &&
               cp config-dist.php config.php
               cp admin/config-dist.php admin/config.php
               php /var/www/html/www/install/cli_install.php install --username admin --password admin --email admin@localhost.local --http_server https://opencart-my-store/ --db_driver mysqli --db_hostname database --db_username opencart --db_password opencart5eyX --db_database opencart3 --db_port 3306 --db_prefix oc_;
               touch /var/www/html/www/install.lock;
             fi && php-fpm"
    restart: always

  database:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./conf/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro
      - data_opencart-3:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cms-network
    environment:
      MYSQL_ROOT_PASSWORD: 'qEmMVrRxEHdRWbdM'
      MYSQL_DATABASE: 'opencart3'
      MYSQL_USER: 'opencart'
      MYSQL_PASSWORD: 'opencart5eyX'
    restart: always
